--Q1. What is the total revenue generated by male vs. female customers?
select gender , SUM(purchase_amount) as total_revenue 
from customer 
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id , purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount>(select AVG(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased , ROUND(AVG(review_rating:: numeric),2) as average_review_rating
from customer
group by item_purchased
order by average_review_rating desc
limit 5 ;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select round(avg(purchase_amount),2) , shipping_type
from customer
where shipping_type IN ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select count(customer_id) , round(avg(purchase_amount),2) as average_spend , sum(purchase_amount) as total_revenue, subscription_status 
from customer
group by subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased , ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as purchases
FROM customer
GROUP BY item_purchased
order by purchases DESC
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal' 
	END AS customer_segment
from customer
)

SELECT customer_segment , COUNT(*) AS Total_Customers
from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
with items_count as(
SELECT item_purchased , category,
count(customer_id) as total_order ,
ROW_NUMBER() OVER(partition by category order by count(customer_id) DESC) as item_rank 
from customer 
group by category , item_purchased
)

select item_rank,item_purchased, category, total_order
from items_count
where item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT count(customer_id) as orders, subscription_status
from customer 
where previous_purchases>5
group by subscription_status;

--Q10. What is the revenue contribution of each age group?
select SUM(purchase_amount) as revenue , age_groups
from customer 
group by age_groups
order by revenue DESC;



